9.GET-articleComments
FatemaZahra/BE-Project-nc-news pull request #8
Opened 2022-05-18 11:59 UTC by FatemaZahra

Added app.js, models, controllers and the test suite for 9.GET /api/articles/:article_id/comments

2022-05-18 12:45 UTC, scar1377 requested changes
Hi Fatema, please follow the feedback and add 200 no comments related to the article

2022-05-18 12:45 UTC, scar1377 commented on __tests__/app.test.js
> +  });
200 for an article that exists but has no comments

2022-05-18 12:45 UTC, scar1377 commented on models/model.js
> +    });
articleComment.rows.length === 0 has two possibilities 1) 404 article doesn't exist;  2)200 no comments related to this article. Think of a way to deal with both the situations

2022-05-18 14:17 UTC, mallionaire requested changes

2022-05-18 14:17 UTC, mallionaire commented on __tests__/app.test.js
> +        expect(comments).toBeInstanceOf(Array);
Must include a check for the length of the array, rather than an instance of an array -  otherwise you could get a false positive from your forEach

2022-05-18 14:17 UTC, mallionaire commented on models/model.js
> +  if (article_id > 36) {
Interesting work around, but what happens when more articles are added. You'll want to explore a more secure way of handling both scenarios. 
Maybe you could make a request for that article_id, to check it exists? 
You might want to take a look at the Promise.all to help with this.

2022-05-19 08:32 UTC, Rosem10 commented
Please split your controllers and model out into their different concerns - eg. you already have one for users, but topics and articles should have their own ones.

2022-05-19 08:37 UTC, Rosem10 reviewed
Please split your models and controllers out into separate concerns - you already have done it with users, but you should also have separate ones of articles, topics etc.

2022-05-19 08:37 UTC, Rosem10 commented on __tests__/app.test.js
> +        expect(comments.length).toBe(0);
This is great - we need the same thing to be added to the test above where it's responding with an array that does have comments, please!

2022-05-19 09:46 UTC, popatre requested changes

2022-05-19 09:46 UTC, popatre commented on __tests__/app.test.js
> +        const { comments } = body;
I can't seem to find a fix for Rose's comment - but this looks like it's still missing the checking of the length, for the array, like you had with the empty one

2022-05-19 10:00 UTC, merged